django_landlord_reviews/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lr/', include('lr.urls'))
]

lr/urls.py
from django.urls import path

from . import views

app_name = 'lr'
urlpatterns = [ 
    path('', views.index, name = 'index'),
    path('terms/', views.terms, name = 'terms'),
    path('add-review/', views.add_review, name = 'add-review'),
    path('add-review/post/', views.add_review_post, name = 'add-review-post'),
    path('add-review/added/', views.review_added, name = 'review-added'),
    path('add-tenent/', views.add_tenent, name = 'add-tenent'),
]

lr/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.

class Landlord(models.Model):
    landlord_id = models.CharField(max_length = 9, primary_key = True)
    landlord_first_name = models.CharField(max_length = 64)
    landlord_last_name = models.CharField(max_length = 64)


class Apartment(models.Model):
    apartment_id = models.IntegerField(primary_key = True)
    street_name = models.CharField(max_length = 64)
    street_number = models.PositiveSmallIntegerField()
    apartment_number = models.PositiveSmallIntegerField()
    city = models.CharField(max_length = 64)


class Tenent(models.Model):
    tenent_id = models.CharField(max_length = 9, primary_key = True)
    tenent_first_name = models.CharField(max_length = 64)
    tenent_last_name = models.CharField(max_length = 64)


class Review(models.Model):
    landlord = models.ForeignKey(Landlord, on_delete = models.CASCADE)
    tenent = models.ForeignKey(Tenent, on_delete = models.CASCADE)
    apartment = models.ForeignKey(Apartment, on_delete = models.CASCADE)

    summary = models.CharField(max_length = 70)
    maintanance_description = models.TextField(max_length = 256)
    maintanance_rating = models.PositiveSmallIntegerField()
    contract_description = models.TextField(max_length = 256)
    contract_rating = models.PositiveSmallIntegerField()
    contact_start = models.DateField()
    contract_end = models.DateField(null=True)
    is_contract_ended = models.BooleanField()
    rent_rate_monthly = models.SmallIntegerField(null=True)
    class Meta:
        unique_together = (("landlord", "tenent", "apartment"),)
    
    def __str__(self):
        return self.summary


class TenentForm(ModelForm):
    class Meta:
        model = Tenent
        fields = ['tenent_id', 'tenent_first_name', 'tenent_last_name']

lr/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse

from .models import TenentForm

# Create your views here.
def index(request):
    return render(request, 'lr/index.html')

def terms(request):
    return render(request, 'lr/terms-and-conditions.htm')

def add_review(request):
    return render(request, 'lr/add-review.html')

def add_review_post(request):
    print(request.POST['summary'])
    return HttpResponseRedirect(reverse('lr:review-added'))

def review_added(request):
    return render(request, 'lr/review-added.html')

def add_tenent(request):
    if request.method == 'POST':
        form = TenentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('lr:review-added'))
    else:
        form = TenentForm()
    return render(request, 'lr/add-tenent.html', {'form': form})

lr/templates/lr/acceptable-usage.htm
{% extends "lr/base.html" %}

{% block title %}
Acceptable usage
{% endblock title %}

{% block content %}
<h1>Acceptable usage</h1>
{% endblock content %}

lr/templates/lr/add-review.html
{% extends "lr/base.html" %}

{% block title %}
Add a review
{% endblock title %}

{% block content %}
<form action="{% url 'lr:add-review-post' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <h1>Add a Review</h1>
    Summarize your review (70 chars max)
    <input type="text" name="summary">
    
    <h3>Address</h3>
    <input type="text" name="city" placeholder="City">
    <input type="text" name="street" placeholder="Street">
    <input type="number" name="street_num" placeholder="Street number">
    <input type="text" name="apartment_num" placeholder="Apartment number">

    <h3>Maintanance</h3>
    <textarea name="maintanance_desc" placeholder="How was the apartment maintained?"></textarea>
    <label for="maintanance_rating">Maintanance rating</label>
    <select name="maintanance_rating">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
    </select>
    <h3>Contract</h3>
    <textarea name="contract_desc" placeholder="How reasonable is the contract? What is unique about it?"></textarea>
    <label for="contract_rating">Contact rating</label>
    <select name="contract_rating">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
    </select>
    <br />
    <label for="moved_in">Moved in</label>
    <input type="date" name="moved_in" placeholder="Date moved in">
    <br />
    <label for="moved_out">Moved out</label>
    <input type="date" name="moved_out" placeholder="Date moved out">
    <br />
    <label for="is_contract_ended">Is contracted ended</label>
    <input type="checkbox" name="is_contract_ended" placeholder="Is contracted ended?" title="Is contracted ended?">
    <br />
    Note: It is advised to leave a review after the contact is over and complete (which can be a while after the contact end date)
    <h4>Occupancy type</h4>
    <select name="occupancy_type">
      <option value="room">Room</option>
      <option value="apartment">Apartment</option>
    </select>
    <input type="number" name="rent" placeholder="Rent per month">

    <h3>Landlord</h3>
    <input type="text" name="landlord_first" placeholder="first name">
    <input type="text" name="landlord_last" placeholder="last name">
    <input type="number" name="landlord_id" placeholder="ID">    
    <br />

    <input type="submit" value="Add">
  </div>
</form>

<hr>
{% endblock content %}

lr/templates/lr/add-tenent.html
{% extends "lr/base.html" %}

{% block title %}
Add a review
{% endblock title %}

{% block content %}
<form action="{% url 'lr:add-tenent' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <h1>Add a Tenent</h1>
    
    {{form}}

    <input type="submit" value="Add">
  </div>
</form>

<hr>
{% endblock content %}

lr/templates/lr/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'lr/css/bootstrap.css' %}">
  {% block style %}
  <style>
    
  </style>
  {% endblock %}
  <title>{% block title%}Landlord reviews{% endblock %}</title>
</head>

<body>
  <div class="bs-component">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary justify-content-between">
      <a class="navbar-brand" href="#">Landlord reviews</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
        <!-- <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
        </ul> -->

        <form class="form-inline my-2 my-lg-0">
          <a class="btn btn-success my-2 my-sm-0" href="{% url 'lr:add-review' %}">Add review</a>
        </form>

        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            Abir
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <button class="dropdown-item" type="button">Profile</button>
            <button class="dropdown-item" type="button">Sign out</button>
          </div>
        </div>
      </div>
    </nav>
    <div id="source-button" class="btn btn-primary btn-xs" style="display: none;">&lt; &gt;</div>
  </div>

  <main>
    <div class="jumbotron">
      <div class="container">
          {% block content %}
        <h1>Welcome to landlord reviews</h1>
        <h3>
          Together we'll make the rental market better!
        </h3>
        <hr>
        {% endblock %}
      </div>
    </div>
  </main>


  <footer class="container-fluid gray-bg">
    <div class="container">
      <div class="row">
        <div class="col-6 col-md">
          <h5>Legal</h5>
          <ul class="list-unstyled text-small">
            <li>
              <a class="text-muted" href="#">Acceptable use policy</a>
            </li>
            <li>
              <a class="text-muted" href="#">take-down policy</a>
            </li>
            <li>
              <a class="text-muted" href="{% url 'lr:terms' %}">Terms and conditions</a>
            </li>
            <li>
              <a class="text-muted" href="#">Privacy</a>
            </li>
            <li>
              <a class="text-muted" href="#">Note to landlords</a>
            </li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>About</h5>
          <ul class="list-unstyled text-small">
            <li>
              <a class="text-muted" href="#">About</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="{% static 'lr/js/bootstrap.min.js' %}"></script>
</body>

</html>

lr/templates/lr/index.html
{% extends "lr/base.html" %}

{% block title %}
Landlord reviews!!
{% endblock title %}

{% block content %}
<h1>Welcome to landlord reviews</h1>
<h3>
  Together we'll make the rental market better!
</h3>
<hr>
{% endblock content %}
      

lr/templates/lr/note-to-landlords.htm
{% extends "lr/base.html" %}

{% block title %}
Note to landlords
{% endblock title %}

{% block content %}
<h1>Note to landlords</h1>
{% endblock content %}

lr/templates/lr/privacy-statment.htm
{% extends "lr/base.html" %}

{% block title %}
Privacy statement
{% endblock title %}

{% block content %}
<h1>Privacy statement</h1>
{% endblock content %}

lr/templates/lr/review-added.html
{% extends "lr/base.html" %}

{% block title %}
Review added
{% endblock title %}

{% block content %}
<h1>Thanks for adding that review</h1>
{% endblock content %}

lr/templates/lr/takedown-policy.htm
{% extends "lr/base.html" %}

{% block title %}
Takedown policy
{% endblock title %}

{% block content %}
<h1>Takedown policy</h1>
{% endblock content %}

lr/templates/lr/terms-and-conditions.htm
{% extends "lr/base.html" %}

{% block title %}
Terms and conditions
{% endblock title %}

{% block content %}
<h1>Terms and conditions</h1>
{% endblock content %}